### ISSUE TITLE
lookup for image and name some times empty

### ISSUE THREAD

**Issue by iOSleep** [Co2333/Privacy-Insight#1]
add support to add region option, like cn/us ?
https://itunes.apple.com/cn/lookup?bundleId=com.tencent.QQMusic
or 
https://itunes.apple.com/lookup?bundleId=com.tencent.QQMusic&country=us

**Comment by Lakr233** [comment]
原来如此 你帮我整理一份国家列表？

**Comment by Lakr233** [comment]
CN DK NL AT CA US GB FI FR DE GR ID IT JP KR MY BR PT RU MX ES SE TH TR VN

**Comment by Lakr233** [comment]
done feb5214
